# Generated by Django 2.1.1 on 2018-09-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('application', models.FileField(upload_to='')),
                ('logo', models.FileField(upload_to='')),
                ('business_license', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
                ('close_date', models.DateTimeField()),
                ('application', models.FileField(upload_to='')),
            ],
        ),
    ]
