# Generated by Django 2.1.1 on 2018-09-14 08:44

from django.db import migrations, models
import utils.custom_path


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180914_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application',
        ),
        migrations.AddField(
            model_name='application',
            name='event_application',
            field=models.FileField(default='1', upload_to=utils.custom_path.event_application_upload_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='business_license',
            field=models.FileField(upload_to=utils.custom_path.event_application_upload_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='logo',
            field=models.FileField(upload_to=utils.custom_path.event_application_upload_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='application_form',
            field=models.FileField(upload_to=utils.custom_path.application_form_upload_path),
        ),
    ]
